-- Implement CTAS Query

-- Create table dept
CREATE TABLE dept (id INT, dname STRING)
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ',';

-- Create table empDetails
CREATE TABLE empDetails (id INT, dname STRING, deptid INT)
  ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ',';

-- CTAS statement
CREATE TABLE emp_join_dept
  AS
  SELECT emp.id, emp.name, dept.dname
    FROM dept, empDetails emp       
    WHERE emp.deptid = dept.id;
