-- Create table empDetails
CREATE TABLE empDetails (id INT, name STRING, deptid INT)
  ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ',';

-- Populate the table with data in HDFS
LOAD DATA INPATH '/cloudwick/hive/empDetails'
  INTO TABLE empDetails;

-- Export hive table to Local File System
INSERT OVERWRITE DIRECTORY '/cloudwick/empDump.csv'
  SELECT id, name, deptid FROM empDetails;

-- ISSUE / ERROR
Query ID = root_20150629181106_0e59ee08-e764-4e3c-887f-6c0e3ae2ba30
Total jobs = 3
Launching Job 1 out of 3
Number of reduce tasks is set to 0 since there's no reduce operator
Starting Job = job_1435626571104_0001, Tracking URL = http://pseudohadoop:8088/proxy/application_1435626571104_0001/
Kill Command = /usr/local/hadoop/default/bin/hadoop job  -kill job_1435626571104_0001
Hadoop job information for Stage-1: number of mappers: 0; number of reducers: 0
2015-06-29 18:11:19,446 Stage-1 map = 0%,  reduce = 0%
Ended Job = job_1435626571104_0001 with errors
Error during job, obtaining debugging information...
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Stage-Stage-1:  HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec
